#include "asm_writer.h"

#include <ida/database.hpp>

#include <cstdlib>
#include <format>
#include <fstream>
#include <sstream>
#include <algorithm>

namespace codedump {

std::string AsmWriter::render(
    const std::map<ida::Address, FunctionSummary> &summaries,
    const std::map<ida::Address, std::string> &annotations,
    PTNEmitter &emitter,
    int callee_depth,
    const std::string &type_decls,
    bool omit_ptn
) {
    // Sort functions by address
    std::vector<ida::Address> sorted_funcs;
    for (const auto &[ea, _] : summaries) {
        sorted_funcs.push_back(ea);
    }
    std::sort(sorted_funcs.begin(), sorted_funcs.end());

    // Get per-instruction hints (skipped entirely when PTN is omitted)
    std::map<ida::Address, std::map<ida::Address, std::vector<std::string>>> hints;
    if (!omit_ptn)
        hints = emitter.per_instruction_hints(callee_depth);

    std::ostringstream out;
    out << "; Assembly dump generated by Code Dumper\n";
    out << "; Functions: " << summaries.size() << "\n\n";
    ida::Result<ida::Address> image_base = ida::database::image_base();
    ida::Address base = image_base ? static_cast<ida::Address>(*image_base) : 0;

    // Prepend recursively-resolved type declarations as comments so the
    // single .asm file is self-contained.
    if (!type_decls.empty()) {
        std::istringstream tds(type_decls);
        std::string line;
        while (std::getline(tds, line)) {
            // Strip the leading "// " that the C dumper uses so the asm
            // comment style stays consistent.
            if (line.rfind("// ", 0) == 0)
                out << "; " << line.substr(3) << "\n";
            else if (line.rfind("//", 0) == 0)
                out << ";" << line.substr(2) << "\n";
            else
                out << "; " << line << "\n";
        }
        out << "\n";
    }

    for (ida::Address ea : sorted_funcs) {
        const auto &summary = summaries.at(ea);

        // Function header
        std::string addr_str = std::format("0x{:X}", summary.func_ea);
        std::string rva_str = std::format("0x{:X}", summary.func_ea - base);
        out << "; ========================================\n";
        out << "; Function: " << summary.func_name << "\n";
        out << "; Offset:   RVA " << rva_str << " EA " << addr_str << "\n";
        if (!summary.incoming_regs.empty() || !summary.outgoing_regs.empty()) {
            auto join = [](const std::set<std::string> &s) -> std::string {
                std::string out;
                for (const auto &r : s) {
                    if (!out.empty()) out += ", ";
                    out += r;
                }
                return out.empty() ? std::string("-") : out;
            };
            out << "; Incoming: " << join(summary.incoming_regs) << "\n";
            out << "; Outgoing: " << join(summary.outgoing_regs) << "\n";
        }

        // PTN annotations for the function
        auto it = annotations.find(ea);
        if (!omit_ptn && it != annotations.end() && !it->second.empty()) {
            // Output each line with ; prefix
            std::istringstream iss(it->second);
            std::string line;
            while (std::getline(iss, line)) {
                if (!line.empty()) {
                    out << "; " << line << "\n";
                }
            }
        }
        out << "; ========================================\n";

        // Disassembly with per-instruction hints
        if (!summary.disassembly.empty()) {
            // Check if we have hints for this function
            auto func_hints = hints.find(ea);
            if (func_hints != hints.end() && !func_hints->second.empty()) {
                // Parse disassembly and insert hints
                std::istringstream diss(summary.disassembly);
                std::string line;
                while (std::getline(diss, line)) {
                    // Extract address from line (format: "addr: instruction")
                    ida::Address line_ea = ida::BadAddress;
                    if (line.length() > 2) {
                        // Try to parse address
                        char *end = nullptr;
                        line_ea = strtoull(line.c_str(), &end, 16);
                        if (end == line.c_str()) {
                            line_ea = ida::BadAddress;
                        }
                    }

                    // Output the line
                    out << line << "\n";

                    // Check for hints at this address
                    if (line_ea != ida::BadAddress) {
                        auto addr_hints = func_hints->second.find(line_ea);
                        if (addr_hints != func_hints->second.end()) {
                            for (const auto &hint : addr_hints->second) {
                                out << "                        ; " << hint << "\n";
                            }
                        }
                    }
                }
            } else {
                out << summary.disassembly;
            }
        } else {
            out << "; (no disassembly available)\n";
        }

        out << "\n";
    }

    return out.str();
}

bool AsmWriter::write(
    const std::string &path,
    const std::map<ida::Address, FunctionSummary> &summaries,
    const std::map<ida::Address, std::string> &annotations,
    PTNEmitter &emitter,
    int callee_depth,
    const std::string &type_decls,
    bool omit_ptn
) {
    std::string text = render(summaries, annotations, emitter, callee_depth,
                              type_decls, omit_ptn);
    std::ofstream out(path);
    if (!out) return false;
    out << text;
    return (bool)out;
}

} // namespace codedump
