#include "code_writer.h"

#include "analysis/function_ranker.h"

#include <ida/database.hpp>

#include <format>
#include <fstream>
#include <sstream>
#include <algorithm>

namespace codedump {

namespace {

std::string hex_addr(ida::Address address) {
    return std::format("0x{:X}", address);
}

} // namespace

std::string CodeWriter::build_header(
    const std::set<ida::Address> &start_functions,
    int caller_depth,
    int callee_depth,
    const std::map<ida::Address, FunctionSummary> &summaries,
    bool omit_ptn,
    const std::vector<ida::Address> &ordered_functions,
    FunctionOrder function_order
) {
    std::ostringstream ss;

    ss << "// Decompiled code dump generated by CodeDumper\n\n";

    // PTN Legend
    if (!omit_ptn) {
        ss << "// --------\n";
        ss << "#PTN v1\n";
        ss << "// @PTN LEGEND\n";
        ss << "// Nodes: L(name)=local; P(name)=param; G(name|addr)=global; C(val)=constant; R(func)=return val.\n";
        ss << "// Slices: @[off:len] or .field_name; '&' = address-of; '*' = deref.\n";
        ss << "// A: alias/assignment => A: dst := src\n";
        ss << "// I: inbound (caller->param) => I: origin -> P(name)\n";
        ss << "// E: outbound (arg->callee)  => E: origin -> A(callee, arg_idx)\n";
        ss << "// R: return flow => R: callee() -> L(var)\n";
        ss << "// G: global access => G: F(func) -> G(addr) (write) or G(addr) -> F(func) (read)\n";
        ss << "// --------\n\n";
    }

    // Start function(s)
    if (start_functions.empty()) {
        ss << "// Start: all functions (no seed resolution)\n";
    } else if (start_functions.size() == 1) {
        ida::Address start_ea = *start_functions.begin();
        auto it = summaries.find(start_ea);
        std::string name = it != summaries.end() ? it->second.func_name : "unknown";
        ss << "// Start Function: " << hex_addr(start_ea) << " (" << name << ")\n";
    } else {
        ss << "// Start Functions:\n";
        for (ida::Address ea : start_functions) {
            auto it = summaries.find(ea);
            std::string name = it != summaries.end() ? it->second.func_name : "unknown";
            ss << "//   - " << hex_addr(ea) << " (" << name << ")\n";
        }
    }

    ss << "// Caller Depth: " << caller_depth << "\n";
    ss << "// Callee/Ref Depth: " << callee_depth << "\n";
    ss << "// Total Functions Found: " << summaries.size() << "\n";
    ss << "// Function Sort: " << function_order_name(function_order) << "\n";

    // List included functions
    ss << "// Included Functions (" << summaries.size() << "):\n";
    for (ida::Address ea : ordered_functions) {
        auto it = summaries.find(ea);
        if (it == summaries.end()) continue;
        ss << "//   - " << it->second.func_name << " (" << hex_addr(ea) << ")\n";
    }

    ss << "// Removed Functions: None\n";
    ss << "// ------------------------------------------------------------\n\n";

    return ss.str();
}

std::string CodeWriter::get_incoming_xrefs(
    ida::Address func_ea,
    const std::vector<Edge> &edges,
    const std::map<ida::Address, FunctionSummary> &summaries
) {
    std::vector<std::string> incoming;

    for (const auto &edge : edges) {
        if (edge.to == func_ea) {
            auto it = summaries.find(edge.from);
            std::string caller_name = it != summaries.end() ? it->second.func_name : "unknown";

            std::string types_str;
            for (RefType rt : edge.types) {
                if (!types_str.empty()) types_str += "/";
                types_str += ref_type_name(rt);
            }

            std::ostringstream entry;
            entry << caller_name << " (" << hex_addr(edge.from) << ") [" << types_str << "]";
            incoming.push_back(entry.str());
        }
    }

    if (incoming.empty()) {
        return "None";
    }

    std::string result;
    for (size_t i = 0; i < incoming.size(); i++) {
        if (i > 0) result += ", ";
        result += incoming[i];
    }
    return result;
}

std::string CodeWriter::get_outgoing_xrefs(
    ida::Address func_ea,
    const std::vector<Edge> &edges,
    const std::map<ida::Address, FunctionSummary> &summaries
) {
    std::vector<std::string> outgoing;

    for (const auto &edge : edges) {
        if (edge.from == func_ea) {
            auto it = summaries.find(edge.to);
            std::string callee_name = it != summaries.end() ? it->second.func_name : "unknown";

            std::string types_str;
            for (RefType rt : edge.types) {
                if (!types_str.empty()) types_str += "/";
                types_str += ref_type_name(rt);
            }

            std::ostringstream entry;
            entry << callee_name << " (" << hex_addr(edge.to) << ") [" << types_str << "]";
            outgoing.push_back(entry.str());
        }
    }

    if (outgoing.empty()) {
        return "None";
    }

    std::string result;
    for (size_t i = 0; i < outgoing.size(); i++) {
        if (i > 0) result += ", ";
        result += outgoing[i];
    }
    return result;
}

std::string CodeWriter::build_function_block(
    ida::Address func_ea,
    const FunctionSummary &summary,
    const std::string &annots,
    const std::vector<Edge> &edges,
    const std::map<ida::Address, FunctionSummary> &all_summaries,
    bool omit_ptn
) {
    std::ostringstream ss;

    std::string addr_text = hex_addr(func_ea);

    // Incoming xrefs
    ss << "// Incoming xrefs for " << summary.func_name << " (" << addr_text << "): "
       << get_incoming_xrefs(func_ea, edges, all_summaries) << "\n";

    // Outgoing xrefs
    ss << "// Outgoing xrefs for " << summary.func_name << " (" << addr_text << "): "
       << get_outgoing_xrefs(func_ea, edges, all_summaries) << "\n";

    // PTN annotations
    if (!omit_ptn && !annots.empty()) {
        ss << annots;
    }

    // Function header
    ss << "// --- Function: " << summary.func_name << " (" << addr_text << ") ---\n";

    // Register liveness summary (only when the user enabled it).
    if (!summary.incoming_regs.empty() || !summary.outgoing_regs.empty()) {
        auto join = [](const std::set<std::string> &s) -> std::string {
            std::string out;
            for (const auto &r : s) {
                if (!out.empty()) out += ", ";
                out += r;
            }
            return out.empty() ? std::string("-") : out;
        };
        ss << "// incoming: " << join(summary.incoming_regs) << "\n";
        ss << "// outgoing: " << join(summary.outgoing_regs) << "\n";
    }

    // Explicit offset comment, kept on its own line right above the
    // function signature so it survives when the user copies just the
    // body out of the dump (named functions don't otherwise carry a
    // sub_XXX hint about their address). Shows both the RVA (image-base
    // relative) and the absolute EA so the user has whichever fits.
    ida::Result<ida::Address> image_base = ida::database::image_base();
    ida::Address base = image_base ? static_cast<ida::Address>(*image_base) : 0;
    ss << "// offset: RVA " << hex_addr(func_ea - base)
       << " EA " << addr_text << "\n";

    // Decompiled code
    if (!summary.decompiled_code.empty()) {
        ss << summary.decompiled_code;
        if (summary.decompiled_code.back() != '\n') {
            ss << "\n";
        }
    } else {
        ss << "// (decompilation failed)\n";
    }

    // End marker
    ss << "// --- End Function: " << summary.func_name << " (" << addr_text << ") ---\n\n";

    return ss.str();
}

std::string CodeWriter::render(
    const std::map<ida::Address, FunctionSummary> &summaries,
    const std::map<ida::Address, std::string> &annotations,
    const std::vector<Edge> &edges,
    const std::set<ida::Address> &start_functions,
    int caller_depth,
    int callee_depth,
    int max_chars,
    const std::string &type_decls,
    bool omit_ptn,
    FunctionOrder function_order
) {
    std::set<ida::Address> function_set;
    for (const auto &[ea, _] : summaries) {
        function_set.insert(ea);
    }
    std::vector<ida::Address> sorted_funcs =
        order_functions(function_set, edges, start_functions, function_order);

    // Build content
    std::string header = build_header(start_functions, caller_depth, callee_depth,
                                      summaries, omit_ptn, sorted_funcs,
                                      function_order);
    header += type_decls;

    std::vector<std::pair<ida::Address, std::string>> blocks;
    for (ida::Address ea : sorted_funcs) {
        const auto &summary = summaries.at(ea);
        std::string annots;
        auto it = annotations.find(ea);
        if (it != annotations.end()) {
            annots = it->second;
        }
        std::string block = build_function_block(ea, summary, annots, edges, summaries, omit_ptn);
        blocks.emplace_back(ea, block);
    }

    // Prune if max_chars is set
    if (max_chars > 0) {
        size_t total = header.size();
        for (const auto &[_, block] : blocks) {
            total += block.size();
        }

        if (total > (size_t)max_chars) {
            // Sort by size, keep largest, but always keep start functions
            std::vector<std::pair<ida::Address, size_t>> removable;
            for (const auto &[ea, block] : blocks) {
                if (start_functions.find(ea) == start_functions.end()) {
                    removable.emplace_back(ea, block.size());
                }
            }
            std::sort(removable.begin(), removable.end(),
                [](const auto &a, const auto &b) { return a.second < b.second; });

            std::set<ida::Address> removed;
            while (total > (size_t)max_chars && !removable.empty()) {
                auto [ea, size] = removable.front();
                removable.erase(removable.begin());
                removed.insert(ea);
                total -= size;
            }

            // Filter blocks
            std::vector<std::pair<ida::Address, std::string>> filtered;
            for (const auto &[ea, block] : blocks) {
                if (removed.find(ea) == removed.end()) {
                    filtered.emplace_back(ea, block);
                }
            }
            blocks = std::move(filtered);
        }
    }

    std::string out = std::move(header);
    for (const auto &[_, block] : blocks) {
        out += block;
    }
    return out;
}

bool CodeWriter::write(
    const std::string &path,
    const std::map<ida::Address, FunctionSummary> &summaries,
    const std::map<ida::Address, std::string> &annotations,
    const std::vector<Edge> &edges,
    const std::set<ida::Address> &start_functions,
    int caller_depth,
    int callee_depth,
    int max_chars,
    const std::string &type_decls,
    bool omit_ptn,
    FunctionOrder function_order
) {
    std::string text = render(summaries, annotations, edges, start_functions,
                              caller_depth, callee_depth, max_chars,
                              type_decls, omit_ptn, function_order);
    std::ofstream out(path);
    if (!out) return false;
    out << text;
    return (bool)out;
}

} // namespace codedump
